import React,{useEffect,useRef,useState} from 'react';
import {Monitor,Play,Square,Send,ShieldCheck,ChevronRight} from 'lucide-react';
import {api,BASE,type Auth} from './api';
import './browser-test.css';
type Status={provider?:string;mode:string;target:string;workerOnline:boolean;workerState:string;status:string;runId:string|null;observedAt:string|null;expiresAt:string|null;failure:string|null;blockers:string[];aiConfigured:boolean;previewAvailable:boolean;executionEnabled:false};
const labels:Record<string,string>={provider_changed:'Casino provider changed; start a new test',provider_switch_pending:'Waiting for the Duel worker update',game_unavailable:'The provider game is unavailable',game_surface_unverified:'Duel blackjack surface could not be verified',offline:'Browser worker offline',ready:'Chromium ready',checking:'Checking Chromium',chromium_sandbox_unavailable:'This host cannot start sandboxed Chromium',chromium_not_installed:'Chromium installation missing',browser_start_or_navigation_failed:'Browser could not start or load the page',operator_session_invalid:'Operator session is missing, expired or invalid',location_restricted:'Provider location restriction',human_verification_required:'Provider requires human verification',access_denied:'Provider denied access',login_required:'Casino login required',sensitive_overlay:'Private overlay detected',game_controls_missing:'Game controls could not be verified',ambiguous_game_controls:'Multiple matching controls found',unexpected_page:'Unexpected page',worker_restarted:'Worker restarted; start a new test',observation_stale:'Observation is no longer current',provider_blocked:'The provider page is blocked',read_only_test_no_verified_hand:'Read-only test. No verified hand is available.',conversation_only:'Conversation; no action requested'};
const label=(s:string)=>labels[s]||s.replaceAll('_',' ');
export default function BrowserTest({auth,connect}:{auth:Auth|null;connect:()=>void}){
 const [status,setStatus]=useState<Status|null>(null),[details,setDetails]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[reply,setReply]=useState<any>(null),[frame,setFrame]=useState('');
 const lastFrame=useRef('');const isOperator=!!auth?.operator;
 useEffect(()=>{let closed=false,timer:ReturnType<typeof setTimeout>;async function poll(){try{const s=await api<Status>('/v1/browser-test');if(closed)return;setStatus(s);setError('');if(isOperator){const d=await api('/v1/browser-test/details');if(!closed)setDetails(d);}}catch(e){if(!closed){setError((e as Error).message);setStatus(null);setDetails(null);}}if(!closed)timer=setTimeout(poll,3000);}void poll();return()=>{closed=true;clearTimeout(timer);};},[auth?.token,isOperator]);
 useEffect(()=>{let closed=false,timer:ReturnType<typeof setTimeout>;const controller=new AbortController();function clear(){if(lastFrame.current)URL.revokeObjectURL(lastFrame.current);lastFrame.current='';setFrame('');}
  clear();if(!isOperator||!status?.previewAvailable||!status.runId||!auth)return;
  async function poll(){try{const r=await fetch(`${BASE}/v1/browser-test/frame?runId=${encodeURIComponent(status!.runId!)}`,{headers:{authorization:`Bearer ${auth!.token}`},credentials:'omit',cache:'no-store',signal:AbortSignal.any([controller.signal,AbortSignal.timeout(4000)])});if(!r.ok||r.status===204){if(!closed)clear();}else{const blob=await r.blob();if(!closed){const url=URL.createObjectURL(blob);if(lastFrame.current)URL.revokeObjectURL(lastFrame.current);lastFrame.current=url;setFrame(url);}}}catch{if(!closed)clear();}if(!closed)timer=setTimeout(poll,1000);}void poll();return()=>{closed=true;clearTimeout(timer);controller.abort();if(lastFrame.current)URL.revokeObjectURL(lastFrame.current);lastFrame.current='';};
 },[auth?.token,isOperator,status?.previewAvailable,status?.runId]);
 async function command(kind:'start'|'stop'){setBusy(true);setError('');setReply(null);try{await api('/v1/browser-test/'+kind,kind==='stop'?{runId:status?.runId}:{});setStatus(await api<Status>('/v1/browser-test'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function interpret(e:React.FormEvent){e.preventDefault();if(!message.trim()||!status?.runId)return;setBusy(true);setError('');try{setReply(await api('/v1/browser-test/interpret',{runId:status.runId,message:message.trim()}));setMessage('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const active=!!status&&['queued','starting','observing'].includes(status.status),observation=details?.observation;
 const title=!status?'Connecting to browser service':!status.workerOnline?'Browser worker is offline':status.workerState!=='ready'?label(status.workerState):status.status==='queued'||status.status==='starting'?'Opening the casino browser':status.status==='blocked'?'The browser test stopped at a blocker':status.status==='failed'?label(status.failure||'browser_start_or_navigation_failed'):status.status==='observing'?'Browser connected. Preview withheld.':'Ready to inspect the casino';
 const result=reply||details?.ai;
 return <div className="page browser-test-page"><div className="section-page-heading heading-with-action"><div><h1>Browser test</h1><p>The selected casino page, inspected by a persistent browser worker.</p></div><span className="browser-test-mode"><ShieldCheck size={14}/>Read-only</span></div>
 <div className="browser-test-layout"><div><section className="browser-test-player"><div className="browser-address"><Monitor size={15}/><span>{status?.target || 'https://duel.com/blackjack'}</span><small>Actual browser</small></div><div className="browser-test-viewport">{frame&&status?.previewAvailable&&isOperator?<img src={frame} alt="Current operator-approved game area from the real casino browser"/>:<div className="browser-test-placeholder"><Monitor size={35}/><h2>{title}</h2><p>{status?.status==='blocked'?'No bypass or repeated navigation is attempted. Resolve the reported blocker before starting another test.':status?.status==='observing'?'A game-only capture area must be configured and approved before images are exposed. The worker is inspecting the real page.':'Start a test to open the configured casino page. No local blackjack game is substituted.'}</p>{status&&status.blockers.length>0&&<ul>{status.blockers.map(b=><li key={b}>{label(b)}</li>)}</ul>}{!auth?<button className="button primary" onClick={connect}>Connect operator wallet</button>:!isOperator?<p className="browser-test-access">Your connected wallet is not an operator.</p>:active?<button className="button ghost" disabled={busy} onClick={()=>command('stop')}><Square size={14}/>Stop test</button>:<button className="button primary" disabled={busy||!status?.workerOnline||status?.workerState!=='ready'} onClick={()=>command('start')}><Play size={15}/>{busy?'Starting…':'Start browser test'}</button>}</div>}</div><div className="browser-test-caption"><span>{frame?'Live browser preview · up to 1 frame/second':'Preview stays hidden during login, unknown state, or access restrictions.'}</span>{frame&&active&&<button className="button ghost" disabled={busy} onClick={()=>command('stop')}>Stop test</button>}</div></section>
 <div className="browser-test-summary"><div><span>Browser</span><strong>{status?status.workerOnline?label(status.workerState):'Offline':'Checking…'}</strong></div><div><span>Run</span><strong>{status?label(status.status):'—'}</strong></div><div><span>Actions executed</span><strong>None · read-only</strong></div></div>{error&&<p role="alert" className="resource-note">{error}</p>}
 <details className="browser-test-details"><summary>Observed controls & test log <ChevronRight size={15}/></summary>{isOperator?<><p>Control visibility does not prove the current hand, bankroll, legal strategy, or settled result.</p>{observation?<div className="browser-controls">{Object.entries(observation.controls).map(([name,value]:[string,any])=><div key={name}><strong>{name}</strong><span>{value.visible} visible · {value.enabled} enabled</span></div>)}</div>:<p>No browser observation yet.</p>}<ol>{details?.events?.map((e:any)=><li key={e.id}><time>{new Date(e.created_at).toLocaleTimeString()}</time><span>{label(e.kind)}</span></li>)}</ol></>:<p>Connect an operator wallet to inspect controls, diagnostics, and the private preview.</p>}</details></div>
 <aside className="browser-test-chat"><div className="browser-test-chat-heading"><h2>Test an instruction</h2><span>{status?.aiConfigured?'AI configured':'AI unavailable'}</span></div><div className="browser-test-conversation"><p>Send a request such as “hit”, “increase the bet”, or “bank”. The model interprets it against the actual page observation.</p><div className="browser-test-rule"><ShieldCheck size={17}/><p>Proposals are shown here but never executed. Testing cannot click Play, place a wager, redeem funds, or control the account.</p></div>{result&&<div className="browser-ai-result" aria-live="polite"><span>Interpreted request</span><strong>{label(result.decision.intent)}</strong><span>Requested action</span><strong>{label(result.decision.proposal)}</strong><p>{label(result.decision.reason)}</p><small>{result.usage.inputTokens+result.usage.outputTokens} tokens{result.usage.estimatedCostUsd!==null?` · estimated $${result.usage.estimatedCostUsd.toFixed(5)}`:''}</small></div>}</div><form onSubmit={interpret}><label htmlFor="browser-test-message">Instruction</label><textarea id="browser-test-message" value={message} onChange={e=>setMessage(e.target.value)} maxLength={500} disabled={!isOperator} placeholder="Ask the browser AI…"/><button className="button primary" disabled={!isOperator||!observation||!status?.aiConfigured||busy||!message.trim()}><Send size={14}/>{busy?'Interpreting…':'Test instruction'}</button><small>{!isOperator?'Operator access required.':'At most 6 requests per minute. No funds required.'}</small></form></aside></div>
 <p className="browser-test-footnote">Tests run for up to five minutes. This checks real browser access, observed controls, safe capture, and AI intent. Automated casino gameplay and settlement are not verified yet.</p></div>;
}
