import React from 'react';
import { House, Compass, Radio, Plus, Wallet, BookOpen, Code2, BarChart3, FlaskConical, Settings2, PanelLeftClose, PanelLeftOpen, X, ArrowUpRight } from 'lucide-react';
const primary=[['/','Explore',Compass],['/live','Live rooms',Radio],['/launch','Launch coin',Plus],['/rewards','Rewards',Wallet]] as const;
const resources=[['/analytics','Analytics',BarChart3],['/documentation','Documentation',BookOpen],['/api','API reference',Code2]] as const;
export const pageTitle=(route:string)=>[...primary,...resources,['/sandbox','Practice table'],['/operations','Operations']].find(x=>x[0]===route)?.[1]||(route.startsWith('/room/')?'Live room':'Explore');
export default function Navigation({route,collapsed,mobileOpen,operator,onToggle,onClose}:{route:string;collapsed:boolean;mobileOpen:boolean;operator:boolean;onToggle:()=>void;onClose:()=>void}){
 function links(items:typeof primary|typeof resources){return items.map(([path,label,Icon])=><a key={path} href={'#'+path} className={route===path?'selected':''} aria-current={route===path?'page':undefined} aria-label={label} title={label} onClick={onClose}><Icon size={19} strokeWidth={1.7}/><span>{label}</span></a>);}
 return <>{mobileOpen&&<button className="navigation-backdrop" aria-label="Close navigation" onClick={onClose}/>}<aside id="site-navigation" className={'site-sidebar '+(mobileOpen?'mobile-open':'')} aria-label="Main navigation"><a href="#/" className="sidebar-brand" aria-label="HOUSE home" onClick={onClose}><span className="brand-mark"><House size={24} strokeWidth={2}/></span><strong>HOUSE</strong></a><button className="mobile-nav-close" aria-label="Close navigation" onClick={onClose}><X size={20}/></button><nav className="side-nav" aria-label="Platform">{links(primary)}<div className="nav-divider"/>{links(resources)}{operator&&<a href="#/operations" className={route==='/operations'?'selected':''} onClick={onClose}><Settings2 size={19}/><span>Operations</span></a>}</nav><div className="sidebar-bottom"><a className={'practice-nav '+(route==='/sandbox'?'selected':'')} href="#/sandbox" onClick={onClose} aria-label="Practice table" title="Practice table"><FlaskConical size={19}/><span>Practice table<small>Free test credits</small></span><ArrowUpRight size={15}/></a><div className="sidebar-meta"><span>HOUSE <small>Early access</small></span><button title={collapsed?'Expand sidebar':'Collapse sidebar'} aria-label={collapsed?'Expand sidebar':'Collapse sidebar'} onClick={onToggle}>{collapsed?<PanelLeftOpen size={18}/>:<PanelLeftClose size={18}/>}</button></div></div></aside></>;
}
