import React, {useEffect, useRef, useState} from 'react';
import {api} from './api';
import './sandbox.css';
type Decision={id:string;kind:string;options:string[];fallback:string;deadline:number;tally:Record<string,number>};
type Room={version:number;session:string;game:string;queued:string|null;phase:string;balance:number;start:number;stake:number;cashout:number;round:number;player:number[];dealer:number[];reels:number[];number:number|null;result:string;decision:Decision|null;serverTime:number;chat:{id:string;name:string;text:string;at:number}[];receipts:{round:number;game:string;stake:number;returned:number;balance:number;result:string}[]};
type Guest={guest:string;token:string;expiresAt:number};
const credits=(n:number)=>(n/100).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2});
const cap=(s:string)=>s[0].toUpperCase()+s.slice(1);
const redNumbers=new Set([1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36]);
function handTotal(cards:number[]){let v=0,a=0;for(const c of cards){if(c<0)continue;const n=c%13;v+=n===0?11:Math.min(n+1,10);if(n===0)a++;}while(v>21&&a--)v-=10;return v;}
function Card({n}:{n:number}){const suits=['♠','♥','♣','♦'];return <div className={'sb-card '+(n<0?'sb-back':Math.floor(n/13)%2?'sb-red':'')}><b>{n<0?'H':['A','2','3','4','5','6','7','8','9','10','J','Q','K'][n%13]}</b><span>{n<0?'':suits[Math.floor(n/13)]}</span></div>;}
export default function Sandbox(){
 const [room,setRoom]=useState<Room|null>(null),[guest,setGuest]=useState<Guest|null>(null),[connected,setConnected]=useState(false),[busy,setBusy]=useState(false),[text,setText]=useState(''),[notice,setNotice]=useState(''),[playerTab,setPlayerTab]=useState('Live game'),[chatOpen,setChatOpen]=useState(true),[clock,setClock]=useState(Date.now()),[vote,setVote]=useState<{id:string;choice:string}|null>(null);
 const offset=useRef(0),joinPromise=useRef<Promise<Guest>|null>(null),chatEnd=useRef<HTMLDivElement>(null),lastResponse=useRef(0);
 function receive(next:Room){if(next.serverTime<lastResponse.current)return;lastResponse.current=next.serverTime;offset.current=next.serverTime-Date.now();setRoom(next);setConnected(true);}
 useEffect(()=>{let disposed=false,timer:ReturnType<typeof setTimeout>;async function refresh(){try{const r=await api<Room>('/v1/sandbox');if(!disposed)receive(r);}catch{if(!disposed)setConnected(false);}if(!disposed)timer=setTimeout(refresh,2000);}void refresh();const t=setInterval(()=>setClock(Date.now()),250);return()=>{disposed=true;clearTimeout(timer);clearInterval(t);};},[]);
 useEffect(()=>{try{const saved=JSON.parse(sessionStorage.getItem('house-sandbox-guest')||'null');if(saved?.expiresAt>Date.now())setGuest(saved);}catch{}},[]);
 useEffect(()=>{const panel=chatEnd.current?.parentElement;if(panel)panel.scrollTop=panel.scrollHeight;},[room?.chat.length]);
 async function identity(){if(guest&&guest.expiresAt>Date.now())return guest;if(!joinPromise.current)joinPromise.current=api<Guest>('/v1/sandbox/join',{}).finally(()=>{joinPromise.current=null;});const g=await joinPromise.current;setGuest(g);try{sessionStorage.setItem('house-sandbox-guest',JSON.stringify(g));}catch{}return g;}
 async function send(kind:string,value?:string){if(!room||busy)return;setBusy(true);setNotice('');try{const g=await identity();const result=await api<{state:Room;error?:string;acknowledgement:string}>('/v1/sandbox/action',{token:g.token,kind,requestId:crypto.randomUUID(),session:room.session,version:room.version,...(room.decision?{decisionId:room.decision.id}:{}),...(value===undefined?{}:{value})});receive(result.state);if(result.error)throw Error(result.error);setNotice(result.acknowledgement);if(kind==='chat')setText('');if(room.decision&&room.decision.options.includes((value||'').toLowerCase()))setVote({id:room.decision.id,choice:value!.toLowerCase()});}catch(e){setNotice((e as Error).message);}finally{setBusy(false);}}
 const remaining=room?.decision?Math.max(0,Math.ceil((room.decision.deadline-clock-offset.current)/1000)):0;
 if(!room)return <div className="page"><h1>Practice table</h1><p>{connected?'Loading…':'Connecting to the test room…'}</p><button className="button ghost" onClick={()=>location.reload()}>Retry connection</button></div>;
 const d=room.decision;const symbols=['🍒','🍋','🔔','⭐','◆','7'];
 return <div className="page sb-page"><div className="sb-heading"><div><a className="muted" href="#/">← Explore</a><h1>HOUSE <em>practice table.</em></h1><p>Free test credits. No deposits, tokens, rewards, or cash value.</p></div><button className="button ghost" onClick={()=>setChatOpen(!chatOpen)}>{chatOpen?"Hide chat":"Show chat"}</button><span className={'tag '+(connected?'on':'')}>{connected?'Shared sandbox':'Disconnected · reconnecting'}</span></div>
 <div className="sb-layout" style={!chatOpen?{gridTemplateColumns:"1fr"}:undefined}><section className="sb-main"><div className="tabs">{["Live game","Graph"].map(t=><button key={t} className={playerTab===t?"selected":""} onClick={()=>setPlayerTab(t)}>{t}</button>)}</div>{playerTab==="Graph"?<CreditGraph room={room}/>:<div className="sb-player"><div className="sb-player-top"><span>RENDERED GAME DEMO · NOT A VIDEO STREAM</span><span>Round {room.round}</span></div><div className="sb-table">
 {room.game==='blackjack'?<><div className="sb-hand"><small>DEALER · {room.dealer.includes(-1)?'?':handTotal(room.dealer)}</small><div>{room.dealer.map((n,i)=><Card key={i} n={n}/>)}</div></div><div className="sb-felt-label">HOUSE<span>BLACKJACK PAYS 3:2</span></div><div className="sb-hand"><small>COMMUNITY · {handTotal(room.player)}</small><div>{room.player.map((n,i)=><Card key={i} n={n}/>)}</div></div></>:
 room.game==='roulette'?<div className="sb-roulette"><div className={'sb-wheel '+(room.phase==='decision'?'sb-spinning':'')}><span style={{color:room.number===0?'#c3f46b':room.number!==null&&redNumbers.has(room.number)?'#ff8484':'white'}}>{room.number??'◎'}</span></div><h2>Red or black?</h2><p>European wheel · single zero · 1:1 payout</p></div>:
 <div className="sb-slots"><small>HOUSE PRACTICE SLOTS</small><div className="sb-reels">{[0,1,2].map(i=><span key={`${room.round}-${i}`}>{symbols[room.reels[i]]||'7'}</span>)}</div><p>3 matching: 10× · 2 matching: 2× total return</p></div>}
 {['waiting','ended'].includes(room.phase)&&<div className="sb-overlay"><h2>{room.phase==='waiting'?'Take a seat.':'Session banked.'}</h2><p>{room.phase==='waiting'?'Start with 100 free test credits.':`${credits(room.cashout)} test credits banked. These cannot be claimed.`}</p><button className="button primary" disabled={busy||!connected} onClick={()=>send('start')}>{busy?'Starting…':room.phase==='waiting'?'Start practice session':'Start fresh · 100 test credits'}</button></div>}
 </div><div className="sb-decision" aria-live="polite">{d?<><div><small>{d.kind==='bank'?'SESSION CHECKPOINT':'COMMUNITY DECISION'}</small><h3>{remaining?`${remaining}s to choose`:'Decision closing…'}</h3><p>{d.kind==='bank'?`${credits(room.balance)} credits available to bank`:`Fallback: ${cap(d.fallback)}`}</p></div><div className="sb-vote-buttons">{d.options.map(o=><button key={o} className={'button '+(vote?.id===d.id&&vote.choice===o?'primary':'ghost')} disabled={!connected||busy||remaining===0} onClick={()=>send('vote',o)}>{o==='bank'?'Bank test credits':cap(o)} <b>{d.tally[o]||0}</b></button>)}</div></>:<div><small>{room.phase==='result'?'SETTLED RESULT':'PRACTICE MODE'}</small><h3>{room.result}</h3>{room.phase==='result'&&<p>Next round starts automatically while the room is open.</p>}</div>}</div></div>}
 <div className="sb-stats">{[['Available credits',credits(room.balance)],['Current stake',credits(['decision'].includes(room.phase)&&d?.kind==='play'?room.stake:0)],['Net settled result',credits((d?.kind==='play'?room.balance+room.stake:room.balance)-room.start)]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
 <div className="sb-switch"><span>Next game</span>{['blackjack','roulette','slots'].map(g=><button className={'button '+((room.queued||room.game)===g?'primary':'ghost')} key={g} disabled={busy||!connected||d?.kind==='bank'} onClick={()=>send('game',g)}>{cap(g)}</button>)}{room.queued&&<small>{cap(room.queued)} queued</small>}</div>
 <details className="sb-rules"><summary>Practice rules & recent results</summary><p>All visitors share this room. Each guest session has one replaceable vote. This tests interaction, not holder eligibility or identity. Chat recognises exact commands: hit, stand, red, black, bank, continue. No AI is used here.</p><p>Stakes are approximately 5% of available test credits, rounded down to 0.20 increments (minimum 0.20). Blackjack uses an infinite deck, dealer stands on all 17s, hit/stand only, and a simple below-17 hit fallback. These are illustrative rules, not Shuffle’s rules or a validated strategy engine.</p><p>Votes last 15 seconds. Ties use the shown fallback. Banking is prompted at profit/loss milestones, at least two minutes apart; a tie banks. Sessions end after ten minutes once the current round settles. Nobody viewing pauses new rounds; open decisions still resolve. Banked credits cannot return to play. A fresh session receives new free credits.</p><div className="sb-history">{room.receipts.map(r=><div key={r.round}><span>#{r.round} · {cap(r.game)}</span><span>Stake {credits(r.stake)}</span><span>Returned {credits(r.returned)}</span><strong>{credits(r.balance)} left</strong></div>)}</div></details>
 </section>{chatOpen&&<aside className="sb-chat"><div className="sb-chat-title"><h3>Table chat</h3><span>Shared room</span></div><div className="sb-messages">{!room.chat.length&&<p className="muted">Say hello, or type your choice during a vote.</p>}{room.chat.map(m=><div className="sb-message" key={m.id}><small>{m.name}<time>{new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</time></small><p>{m.text}</p></div>)}<div ref={chatEnd}/></div><form onSubmit={e=>{e.preventDefault();void send('chat',text);}}><label className="sr-only" htmlFor="sb-chat-input">Chat message</label><input id="sb-chat-input" value={text} onChange={e=>setText(e.target.value)} placeholder="Message or vote…" maxLength={240} disabled={!connected}/><button className="button primary" disabled={!connected||busy||!text.trim()}>Send</button></form><p className="sb-notice" role="status">{notice||'Guest access · no wallet needed'}</p></aside>}</div></div>;
}

function CreditGraph({room}:{room:Room}){const values=[room.start,...[...room.receipts].reverse().map(r=>r.balance)];const lo=Math.min(...values)*.9,hi=Math.max(...values)*1.1;const points=values.map((n,i)=>`${20+i*760/Math.max(1,values.length-1)},${270-(n-lo)/(hi-lo||1)*240}`).join(' ');return <div className="sb-graph"><h2>Test-credit balance</h2><p>This is the practice session balance, not a token price chart.</p><svg viewBox="0 0 800 300" role="img" aria-label="Practice balance over settled rounds"><path d="M20 30V270H780" fill="none" stroke="#344338"/><polyline fill="none" stroke="#bbf35b" strokeWidth="3" points={points}/></svg><p>Starting: {credits(room.start)} · Latest settled: {credits(values.at(-1)!)} credits</p></div>;}
